### ISSUE TITLE
Plugin Crashes on Krita Open

### ISSUE THREAD

**Issue by The-True-Foe-Hammer** [poipoi300/auto-sd-krita-ext-xl#4]
**Describe the bug**
It seems certain plugin windows crash when Krita loads, making the plugin unusable in Krita.

**To Reproduce**
1. Install the plug in according to instructions
2. Upon restarting Krita the plugin loads with three errors and is unusable as the only plugin windows available are SD Plugin Config, SD Common Options, Live Preview, and Upscale

**Screenshots**
I don't know that it will really help, but here is what loads:
![Screenshot from 2023-09-08 22-30-22](https://github.com/poipoi300/auto-sd-krita-ext-xl/assets/107009693/1620c685-5eba-4f60-ab3f-50dc25ce0299)

- Screenshot of backend console output
![Screenshot from 2023-09-08 22-41-26](https://github.com/poipoi300/auto-sd-krita-ext-xl/assets/107009693/561aa8c6-5af1-4d6e-8627-50c07cdf1cd8)

--------------------------------------------------------------------------
ERROR POPUP 1
--------------------------------------------------------------------------
TypeError: unhashable type: 'list'
TypeError
Python 3.10.13: /usr/bin/python3
Fri Sep  8 22:00:39 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /app/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'krita_diff.docker.create_docker.<locals>.Docker'>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py in __init__(self=<krita_diff.docker.create_docker.<locals>.Docker object>, *args=(), **kwargs={})
   11             self.setWindowTitle(page.name)
   12             self.create_interface()
   13             self.update_interface()
   14             self.connect_interface()
   15             self.setWidget(self.widget)
self = <krita_diff.docker.create_docker.<locals>.Docker object>
self.update_interface = <bound method create_docker.<locals>.Docker.upda...iff.docker.create_docker.<locals>.Docker object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py in update_interface(self=<krita_diff.docker.create_docker.<locals>.Docker object>)
   23 
   24         def update_interface(self):
   25             self.page_widget.cfg_init()
   26 
   27         def connect_interface(self):
self = <krita_diff.docker.create_docker.<locals>.Docker object>
self.page_widget = <krita_diff.pages.txt2img.Txt2ImgPage object>
self.page_widget.cfg_init = <bound method Txt2ImgPage.cfg_init of <krita_diff.pages.txt2img.Txt2ImgPage object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/txt2img.py in cfg_init(self=<krita_diff.pages.txt2img.Txt2ImgPage object>)
   30 
   31     def cfg_init(self):
   32         super(Txt2ImgPage, self).cfg_init()
   33         self.highres.cfg_init()
   34 
builtinsuper = <class 'super'>
global Txt2ImgPage = <class 'krita_diff.pages.txt2img.Txt2ImgPage'>
self = <krita_diff.pages.txt2img.Txt2ImgPage object>
).cfg_init = <bound method Txt2ImgPage.cfg_init of <krita_diff.pages.txt2img.Txt2ImgPage object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img_base.py in cfg_init(self=<krita_diff.pages.txt2img.Txt2ImgPage object>)
   71 
   72     def cfg_init(self):
   73         self.ext_layout.cfg_init()
   74         self.prompt_layout.cfg_init()
   75         self.seed_layout.cfg_init()
self = <krita_diff.pages.txt2img.Txt2ImgPage object>
self.ext_layout = <krita_diff.pages.extension.ExtSectionLayout object>
self.ext_layout.cfg_init = <bound method ExtSectionLayout.cfg_init of <krita_diff.pages.extension.ExtSectionLayout object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in cfg_init(self=<krita_diff.pages.extension.ExtSectionLayout object>)
  118             self._init_ext_widgets()
  119         for widget in self.ext_widgets.values():
  120             widget.cfg_init()
  121 
  122     def cfg_connect(self):
widget = <krita_diff.pages.extension.ExtWidget object>
widget.cfg_init = <bound method ExtWidget.cfg_init of <krita_diff.pages.extension.ExtWidget object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in cfg_init(self=<krita_diff.pages.extension.ExtWidget object>)
   69     def cfg_init(self):
   70         for w in self.widgets:
   71             w.cfg_init()
   72 
   73     def cfg_connect(self):
w = <krita_diff.widgets.combo_box.QComboBoxLayout object>
w.cfg_init = <bound method QComboBoxLayout.cfg_init of <krita_diff.widgets.combo_box.QComboBoxLayout object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/widgets/combo_box.py in cfg_init(self=<krita_diff.widgets.combo_box.QComboBoxLayout object>)
   68     def cfg_init(self):
   69         opts = sorted(
   70             set(
   71                 self.cfg(self.options_cfg, "QStringList")
   72                 if isinstance(self.options_cfg, str)
builtinset = <class 'set'>
self = <krita_diff.widgets.combo_box.QComboBoxLayout object>
self.cfg = <krita_diff.config.Config object>
self.options_cfg = [['positive', 'positive'], ['negative', 'negative']]
builtinisinstance = <built-in function isinstance>
builtinstr = <class 'str'>
TypeError: unhashable type: 'list'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("unhashable type: 'list'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/app/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py", line 13, in __init__
    self.update_interface()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py", line 25, in update_interface
    self.page_widget.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/txt2img.py", line 32, in cfg_init
    super(Txt2ImgPage, self).cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img_base.py", line 73, in cfg_init
    self.ext_layout.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 120, in cfg_init
    widget.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 71, in cfg_init
    w.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/widgets/combo_box.py", line 70, in cfg_init
    set(
TypeError: unhashable type: 'list'

--------------------------------------------------------------------------
ERROR POPUP 2
--------------------------------------------------------------------------
TypeError: arguments did not match any overloaded call:
QCheckBox(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
QCheckBox(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'

TypeError
Python 3.10.13: /usr/bin/python3
Fri Sep  8 22:03:32 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /app/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'krita_diff.docker.create_docker.<locals>.Docker'>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py in __init__(self=<krita_diff.docker.create_docker.<locals>.Docker object>, *args=(), **kwargs={})
   11             self.setWindowTitle(page.name)
   12             self.create_interface()
   13             self.update_interface()
   14             self.connect_interface()
   15             self.setWidget(self.widget)
self = <krita_diff.docker.create_docker.<locals>.Docker object>
self.update_interface = <bound method create_docker.<locals>.Docker.upda...iff.docker.create_docker.<locals>.Docker object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py in update_interface(self=<krita_diff.docker.create_docker.<locals>.Docker object>)
   23 
   24         def update_interface(self):
   25             self.page_widget.cfg_init()
   26 
   27         def connect_interface(self):
self = <krita_diff.docker.create_docker.<locals>.Docker object>
self.page_widget = <krita_diff.pages.img2img.Img2ImgPage object>
self.page_widget.cfg_init = <bound method Img2ImgPage.cfg_init of <krita_diff.pages.img2img.Img2ImgPage object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img2img.py in cfg_init(self=<krita_diff.pages.img2img.Img2ImgPage object>)
   23 
   24     def cfg_init(self):
   25         super(Img2ImgPage, self).cfg_init()
   26 
   27         self.tips.setVisible(not script.cfg("minimize_ui", bool))
builtinsuper = <class 'super'>
global Img2ImgPage = <class 'krita_diff.pages.img2img.Img2ImgPage'>
self = <krita_diff.pages.img2img.Img2ImgPage object>
).cfg_init = <bound method Img2ImgPage.cfg_init of <krita_diff.pages.img2img.Img2ImgPage object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img_base.py in cfg_init(self=<krita_diff.pages.img2img.Img2ImgPage object>)
   71 
   72     def cfg_init(self):
   73         self.ext_layout.cfg_init()
   74         self.prompt_layout.cfg_init()
   75         self.seed_layout.cfg_init()
self = <krita_diff.pages.img2img.Img2ImgPage object>
self.ext_layout = <krita_diff.pages.extension.ExtSectionLayout object>
self.ext_layout.cfg_init = <bound method ExtSectionLayout.cfg_init of <krita_diff.pages.extension.ExtSectionLayout object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in cfg_init(self=<krita_diff.pages.extension.ExtSectionLayout object>)
  116         self.dropdown.cfg_init()
  117         if set(self.ext_names()) != set(self.ext_widgets.keys()):
  118             self._init_ext_widgets()
  119         for widget in self.ext_widgets.values():
  120             widget.cfg_init()
self = <krita_diff.pages.extension.ExtSectionLayout object>
self._init_ext_widgets = <bound method ExtSectionLayout._init_ext_widgets...ta_diff.pages.extension.ExtSectionLayout object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in _init_ext_widgets(self=<krita_diff.pages.extension.ExtSectionLayout object>)
  107         self._clear_ext_widgets()
  108         for ext_name in self.ext_names():
  109             widget = ExtWidget(script.ext_cfg, self.ext_type, ext_name)
  110             widget.setVisible(False)
  111             self.addWidget(widget)
widget = <krita_diff.pages.extension.ExtWidget object>
global ExtWidget = <class 'krita_diff.pages.extension.ExtWidget'>
global script = <krita_diff.script.Script object>
script.ext_cfg = <krita_diff.config.Config object>
self = <krita_diff.pages.extension.ExtSectionLayout object>
self.ext_type = 'scripts_img2img'
ext_name = 'Outpainting mk2'

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in __init__(self=<krita_diff.pages.extension.ExtWidget object>, ext_cfg=<krita_diff.config.Config object>, ext_type='scripts_img2img', ext_name='Outpainting mk2', *args=(), **kwargs={})
   57                 w = QCheckBox(ext_cfg, k, o["label"])
   58             elif o["type"] == "multiselect":
   59                 w = QMultiCheckBoxLayout(ext_cfg, o["opts"], k, o["label"])
   60             else:
   61                 continue
w = None
global QMultiCheckBoxLayout = <class 'krita_diff.widgets.checkbox.QMultiCheckBoxLayout'>
ext_cfg = <krita_diff.config.Config object>
o = {'is_index': False, 'label': 'Outpainting direction', 'opts': [['left', 'left'], ['right', 'right'], ['up', 'up'], ['down', 'down']], 'type': 'multiselect', 'val': ['left', 'right', 'up', 'down']}
k = 'scripts_img2img_outpaintingmk2_3'

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/widgets/checkbox.py in __init__(self=<krita_diff.widgets.checkbox.QMultiCheckBoxLayout object>, cfg=<krita_diff.config.Config object>, options_cfg=[['left', 'left'], ['right', 'right'], ['up', 'up'], ['down', 'down']], selected_cfg='scripts_img2img_outpaintingmk2_3', label='Outpainting direction', *args=(), **kwargs={})
   61         self.qcheckboxes = []
   62         for opt in self.options_cfg:
   63             checkbox = _QCheckBox(opt)
   64             self.qcheckboxes.append(checkbox)
   65             self.row.addWidget(checkbox)
checkbox undefined
global _QCheckBox = <class 'PyQt5.QtWidgets.QCheckBox'>
opt = ['left', 'left']
TypeError: arguments did not match any overloaded call:
  QCheckBox(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
  QCheckBox(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  Q...t] = None): argument 1 has unexpected type 'list'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/app/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py", line 13, in __init__
    self.update_interface()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py", line 25, in update_interface
    self.page_widget.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img2img.py", line 25, in cfg_init
    super(Img2ImgPage, self).cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img_base.py", line 73, in cfg_init
    self.ext_layout.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 118, in cfg_init
    self._init_ext_widgets()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 109, in _init_ext_widgets
    widget = ExtWidget(script.ext_cfg, self.ext_type, ext_name)
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 59, in __init__
    w = QMultiCheckBoxLayout(ext_cfg, o["opts"], k, o["label"])
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/widgets/checkbox.py", line 63, in __init__
    checkbox = _QCheckBox(opt)
TypeError: arguments did not match any overloaded call:
  QCheckBox(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
  QCheckBox(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'

--------------------------------------------------------------------------
ERROR POPUP 3
--------------------------------------------------------------------------
TypeError: arguments did not match any overloaded call:
QCheckBox(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
QCheckBox(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'

TypeError
Python 3.10.13: /usr/bin/python3
Fri Sep  8 22:07:35 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /app/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'krita_diff.docker.create_docker.<locals>.Docker'>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py in __init__(self=<krita_diff.docker.create_docker.<locals>.Docker object>, *args=(), **kwargs={})
   11             self.setWindowTitle(page.name)
   12             self.create_interface()
   13             self.update_interface()
   14             self.connect_interface()
   15             self.setWidget(self.widget)
self = <krita_diff.docker.create_docker.<locals>.Docker object>
self.update_interface = <bound method create_docker.<locals>.Docker.upda...iff.docker.create_docker.<locals>.Docker object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py in update_interface(self=<krita_diff.docker.create_docker.<locals>.Docker object>)
   23 
   24         def update_interface(self):
   25             self.page_widget.cfg_init()
   26 
   27         def connect_interface(self):
self = <krita_diff.docker.create_docker.<locals>.Docker object>
self.page_widget = <krita_diff.pages.inpaint.InpaintPage object>
self.page_widget.cfg_init = <bound method InpaintPage.cfg_init of <krita_diff.pages.inpaint.InpaintPage object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/inpaint.py in cfg_init(self=<krita_diff.pages.inpaint.InpaintPage object>)
   67 
   68     def cfg_init(self):
   69         super(InpaintPage, self).cfg_init()
   70         # self.mask_blur_layout.cfg_init()
   71         self.fill_layout.cfg_init()
builtinsuper = <class 'super'>
global InpaintPage = <class 'krita_diff.pages.inpaint.InpaintPage'>
self = <krita_diff.pages.inpaint.InpaintPage object>
).cfg_init = <bound method InpaintPage.cfg_init of <krita_diff.pages.inpaint.InpaintPage object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img_base.py in cfg_init(self=<krita_diff.pages.inpaint.InpaintPage object>)
   71 
   72     def cfg_init(self):
   73         self.ext_layout.cfg_init()
   74         self.prompt_layout.cfg_init()
   75         self.seed_layout.cfg_init()
self = <krita_diff.pages.inpaint.InpaintPage object>
self.ext_layout = <krita_diff.pages.extension.ExtSectionLayout object>
self.ext_layout.cfg_init = <bound method ExtSectionLayout.cfg_init of <krita_diff.pages.extension.ExtSectionLayout object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in cfg_init(self=<krita_diff.pages.extension.ExtSectionLayout object>)
  116         self.dropdown.cfg_init()
  117         if set(self.ext_names()) != set(self.ext_widgets.keys()):
  118             self._init_ext_widgets()
  119         for widget in self.ext_widgets.values():
  120             widget.cfg_init()
self = <krita_diff.pages.extension.ExtSectionLayout object>
self._init_ext_widgets = <bound method ExtSectionLayout._init_ext_widgets...ta_diff.pages.extension.ExtSectionLayout object>>

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in _init_ext_widgets(self=<krita_diff.pages.extension.ExtSectionLayout object>)
  107         self._clear_ext_widgets()
  108         for ext_name in self.ext_names():
  109             widget = ExtWidget(script.ext_cfg, self.ext_type, ext_name)
  110             widget.setVisible(False)
  111             self.addWidget(widget)
widget = <krita_diff.pages.extension.ExtWidget object>
global ExtWidget = <class 'krita_diff.pages.extension.ExtWidget'>
global script = <krita_diff.script.Script object>
script.ext_cfg = <krita_diff.config.Config object>
self = <krita_diff.pages.extension.ExtSectionLayout object>
self.ext_type = 'scripts_inpaint'
ext_name = 'Outpainting mk2'

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py in __init__(self=<krita_diff.pages.extension.ExtWidget object>, ext_cfg=<krita_diff.config.Config object>, ext_type='scripts_inpaint', ext_name='Outpainting mk2', *args=(), **kwargs={})
   57                 w = QCheckBox(ext_cfg, k, o["label"])
   58             elif o["type"] == "multiselect":
   59                 w = QMultiCheckBoxLayout(ext_cfg, o["opts"], k, o["label"])
   60             else:
   61                 continue
w = None
global QMultiCheckBoxLayout = <class 'krita_diff.widgets.checkbox.QMultiCheckBoxLayout'>
ext_cfg = <krita_diff.config.Config object>
o = {'is_index': False, 'label': 'Outpainting direction', 'opts': [['left', 'left'], ['right', 'right'], ['up', 'up'], ['down', 'down']], 'type': 'multiselect', 'val': ['left', 'right', 'up', 'down']}
k = 'scripts_inpaint_outpaintingmk2_3'

 /home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/widgets/checkbox.py in __init__(self=<krita_diff.widgets.checkbox.QMultiCheckBoxLayout object>, cfg=<krita_diff.config.Config object>, options_cfg=[['left', 'left'], ['right', 'right'], ['up', 'up'], ['down', 'down']], selected_cfg='scripts_inpaint_outpaintingmk2_3', label='Outpainting direction', *args=(), **kwargs={})
   61         self.qcheckboxes = []
   62         for opt in self.options_cfg:
   63             checkbox = _QCheckBox(opt)
   64             self.qcheckboxes.append(checkbox)
   65             self.row.addWidget(checkbox)
checkbox undefined
global _QCheckBox = <class 'PyQt5.QtWidgets.QCheckBox'>
opt = ['left', 'left']
TypeError: arguments did not match any overloaded call:
  QCheckBox(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
  QCheckBox(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  Q...t] = None): argument 1 has unexpected type 'list'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/app/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py", line 13, in __init__
    self.update_interface()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/docker.py", line 25, in update_interface
    self.page_widget.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/inpaint.py", line 69, in cfg_init
    super(InpaintPage, self).cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/img_base.py", line 73, in cfg_init
    self.ext_layout.cfg_init()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 118, in cfg_init
    self._init_ext_widgets()
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 109, in _init_ext_widgets
    widget = ExtWidget(script.ext_cfg, self.ext_type, ext_name)
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/pages/extension.py", line 59, in __init__
    w = QMultiCheckBoxLayout(ext_cfg, o["opts"], k, o["label"])
  File "/home/mattvg/.var/app/org.kde.krita/data/krita/pykrita/krita_diff/widgets/checkbox.py", line 63, in __init__
    checkbox = _QCheckBox(opt)
TypeError: arguments did not match any overloaded call:
  QCheckBox(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'
  QCheckBox(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'list'

**Desktop (please complete the following information):**
 - OS: Linux
 - WebUI commit revision 5ef669de080814067961f28357256e8fe27544f4
 - Extension commit revision 5cb84e89294665dac172012fab8cde2d22254db0

**Additional context**

**Comment by poipoi300** [comment]
Thanks for opening an issue. This seems to be very similar to #2. For them it was fixed when launching the stable diffusion backend before krita, then launching and closing krita twice. Hopefully this fixes your issue while I work on a real fix. The cause seems pretty clear, I can likely fix it Sunday (EST). Keeping the issue open just in case fixing #2 doesn't fix it for you.

**Comment by Rogal80** [comment]
Hi , for me it doesn't work - I am using krita 5.2

**Comment by ruizray** [comment]
Tried the steps mentioned in that other post as well as reinstalling the extension and can confirm it still doesnt work.

**Comment by poipoi300** [comment]
Issue is confirmed reproducible. Caused by latest WebUI release on new installs only. Can't fix today unfortunately. There are also more issues than just this if you do get it past and showing generation related tabs (regardless of old or new install). 

For now please revert to an older version of the WebUI to use the extension. I need to learn a bit more about the code to be able to fix this. Going to use #2 to track progress on this from now, too. Please refer to that issue for future updates. Thanks again for opening an issue. Prior to this I was under the impression that it was an isolated issue, but I see now that everyone should be getting this issue on new installs.
